Repository brigadecore/brigade, pull requests merged in 2018-08, with the labels that each got.

#583 fix(brigade, worker): fixing a few minor nits
  brigade-worker/src/events.ts
  brigade.js
Labels: bug

#588 feat(brig): add -f flag to rerun command
  brig/cmd/brig/commands/rerun.go
Labels: awaiting review

#589 fix(chart): set max builds to -1 by default
  charts/brigade/values.yaml
Labels: awaiting review, bug

#591 fix(brig): set a default sidecar
  brig/cmd/brig/commands/project_create.go
  brigade-worker/prestart.js
Labels: awaiting review, bug

#618 fix(*): add project default script to worker
  brigade-controller/cmd/brigade-controller/controller/controller_test.go
  brigade-controller/cmd/brigade-controller/controller/handler.go
  brigade-worker/prestart.js
  charts/brigade-project/values.yaml
Labels: bug
