Repository brigadecore/brigade, pull requests merged in 2019-01, with the labels that each got.

#715 fix(charts/brigade-project): allow vcs-sidecar NONE
  brig/cmd/brig/commands/project_create.go
  brigade-controller/cmd/brigade-controller/controller/handler.go
  brigade-controller/cmd/brigade-controller/controller/handler_test.go
  brigade-worker/src/k8s.ts
  brigade-worker/test/k8s.ts
Labels: review

#728 show job logs (#643)
  brigade-worker/src/job.ts
  brigade-worker/src/k8s.ts
  docs/intro/tutorial04.md
  docs/topics/javascript.md
Labels: review

#738 Add GitHub issue and PR templates
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: awaiting review

#759 Use the job shell when starting the container
  brigade-worker/src/k8s.ts
  brigade-worker/test/k8s.ts
Labels: enhancement, review
