Repository brigadecore/brigade, pull requests merged in 2021-08, with the labels that each got.

#1519 start using brigade foundations
  v2/apiserver/Dockerfile
  v2/apiserver/config.go
  v2/apiserver/internal/core/kubernetes/logs_store.go
  v2/apiserver/internal/core/logs.go
  v2/apiserver/internal/lib/crypto/crypto.go
  v2/apiserver/internal/lib/queue/amqp/writer.go
  v2/apiserver/internal/lib/restmachinery/server.go
  v2/apiserver/main.go
  v2/cli/config.go
  v2/cli/event_commands.go
  v2/cli/init_command.go
  v2/cli/init_command_test.go
  v2/cli/main.go
  v2/git-initializer/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/file/file.go
  v2/internal/file/file_test.go
  v2/internal/kubernetes/client.go
  v2/internal/os/os.go
  v2/internal/os/os_test.go
  v2/internal/rand/seeded.go
  v2/internal/rand/seeded_test.go
  v2/internal/retries/retries.go
  v2/internal/retries/retries_test.go
  v2/internal/signals/signals.go
  v2/internal/signals/signals_test.go
  v2/internal/version/version.go
  v2/internal/version/version_test.go
  v2/observer/Dockerfile
  v2/observer/config.go
  v2/observer/main.go
  v2/observer/observer.go
  v2/scheduler/Dockerfile
  v2/scheduler/config.go
  v2/scheduler/internal/lib/queue/amqp/reader.go
  v2/scheduler/jobs.go
  v2/scheduler/main.go
  v2/scheduler/scheduler.go
  v2/scheduler/workers.go
Labels: 2.0

#1524 update readme with info about expanding ecosystem
  README.md
Labels: docs, 2.0

#1525 use crypto.Hash from brigade-foundations
  v2/apiserver/config.go
  v2/apiserver/internal/authn/service_accounts.go
  v2/apiserver/internal/authn/sessions.go
  v2/apiserver/internal/authn/sessions_test.go
  v2/apiserver/internal/core/events.go
  v2/apiserver/internal/lib/crypto/crypto.go
  v2/apiserver/internal/lib/crypto/crypto_test.go
  v2/apiserver/internal/system/authn/token_auth.go
  v2/apiserver/internal/system/authn/token_auth_test.go
  v2/go.mod
  v2/go.sum
Labels: 2.0

#1511 docs(*): fill out roles index and overviews for each
  docs/content/topics/_index.md
  docs/content/topics/administrators/_index.md
  docs/content/topics/administrators/authentication.md
  docs/content/topics/administrators/authorization.md
  docs/content/topics/operators/_index.md
  docs/content/topics/project-developers/_index.md
  docs/content/topics/project-developers/brig.md
  docs/content/topics/project-developers/brigterm.md
  docs/content/topics/project-developers/events.md
  docs/content/topics/project-developers/projects.md
  docs/content/topics/project-developers/secrets.md
  docs/content/topics/roles.md
Labels: docs, 2.0

#1527 update link in readme for brigade-bitbucket-gateway
  README.md
Labels: docs, 2.0

#1518 docs(operator): add deploy doc
  docs/content/intro/install.md
  docs/content/topics/operators/deploy.md
  docs/content/topics/operators/security.md
Labels: docs, 2.0

#1530 update examples so all subscribe to events from cli
  examples/01-hello-world/project.yaml
  examples/06-git/project.yaml
  examples/07-npm/project.yaml
  examples/08-yarn/project.yaml
  examples/09-typescript/project.yaml
  examples/12-first-payload/project.yaml
Labels: 2.0

#1552 Uncommented project.yaml and js/ts script files
  v2/cli/init_templates.go
Labels: 2.0

#1551 fix readnext link; adjust ordering of install and quickstart docs
  docs/config.toml
  docs/content/intro/_index.md
  docs/content/intro/install.md
  docs/content/intro/quickstart.md
Labels: 2.0

#1554 docs(install.md): add note around gateways
  docs/content/intro/install.md
Labels: docs, 2.0

#1557 address known vulnerabilities in npm packages
  v2/brigadier-polyfill/package.json
  v2/brigadier-polyfill/yarn.lock
  v2/worker/yarn.lock
Labels: 2.0, security

#1555 Added brig init instructions to quickstart
  docs/content/intro/quickstart.md
Labels: docs, 2.0

#1558 Removed mention of commented out code in init template files
  v2/cli/init_templates.go
Labels: 2.0

#1550 build cli for arm64
  .brigade/brigade.ts
  Makefile
  scripts/build-cli.sh
  v2/apiserver/Dockerfile
  v2/git-initializer/Dockerfile
  v2/observer/Dockerfile
  v2/scheduler/Dockerfile
Labels: 2.0

#1560 add startup message to git initializer
  v2/git-initializer/Dockerfile
  v2/git-initializer/main.go
Labels: 2.0

#1553 fix(kind/new-cluster): prevent error when kind cluster already exists
  docs/content/topics/developers.md
  hack/kind/new-cluster.sh
Labels: 2.0

#1559 fix: delete all associated events on project delete
  v2/apiserver/internal/api/events.go
  v2/apiserver/internal/api/events_test.go
  v2/apiserver/internal/api/mongodb/events_store.go
  v2/apiserver/internal/api/mongodb/events_store_test.go
  v2/apiserver/internal/api/projects.go
  v2/apiserver/internal/api/projects_test.go
Labels: bug, 2.0

#1562 make README.md reference quickstart
  README.md
Labels: docs, 2.0

#1556 docs(projects.md): v2 updates
  docs/content/topics/project-developers/projects.md
Labels: docs, 2.0

#1565 explicitly direct user to NOTES.txt after brig init
  v2/cli/init_command.go
Labels: 2.0

#1564 explicitly disable user management functions when 3rd party authn is disabled
  v2/apiserver/config.go
  v2/apiserver/config_test.go
  v2/apiserver/internal/api/users.go
  v2/apiserver/internal/api/users_test.go
  v2/apiserver/main.go
Labels: 2.0

#1566 add user delete functionality
  sdk/v2/authn/users.go
  sdk/v2/authn/users_test.go
  sdk/v2/testing/authn/mock_users_client.go
  v2/apiserver/internal/api/mongodb/project_role_assignments_store.go
  v2/apiserver/internal/api/mongodb/project_role_assignments_store_test.go
  v2/apiserver/internal/api/mongodb/role_assignments_store.go
  v2/apiserver/internal/api/mongodb/role_assignments_store_test.go
  v2/apiserver/internal/api/mongodb/users_store.go
  v2/apiserver/internal/api/mongodb/users_store_test.go
  v2/apiserver/internal/api/project_role_assignments.go
  v2/apiserver/internal/api/project_role_assignments_test.go
  v2/apiserver/internal/api/projects_test.go
  v2/apiserver/internal/api/rest/users_endpoints.go
  v2/apiserver/internal/api/role_assignments.go
  v2/apiserver/internal/api/role_assignments_test.go
  v2/apiserver/internal/api/users.go
  v2/apiserver/internal/api/users_test.go
  v2/apiserver/main.go
  v2/cli/user_commands.go
Labels: 2.0

#1568 add service account delete functionality
  sdk/v2/authn/service_accounts.go
  sdk/v2/authn/service_accounts_test.go
  sdk/v2/testing/authn/mock_service_accounts_client.go
  v2/apiserver/internal/api/mongodb/service_accounts_store.go
  v2/apiserver/internal/api/mongodb/service_accounts_store_test.go
  v2/apiserver/internal/api/rest/service_account_endpoints.go
  v2/apiserver/internal/api/service_accounts.go
  v2/apiserver/internal/api/service_accounts_test.go
  v2/apiserver/main.go
  v2/cli/service_account_commands.go
Labels: 2.0

#1572 update docs to mention new docker hub gateway
  README.md
  docs/content/intro/install.md
Labels: docs, 2.0

#1574 add brigade-acr-gateway to docs
  README.md
  docs/content/intro/install.md
Labels: docs, 2.0

#1571 docs(authentication.md): add authentication doc
  docs/content/topics/administrators/authentication.md
  docs/content/topics/operators/deploy.md
Labels: docs, 2.0

#1569 docs(gateways.md): v2 updates
  docs/content/intro/install.md
  docs/content/topics/operators/gateways.md
  examples/gateways/example-gateway/.gitignore
  examples/gateways/example-gateway/go.mod
  examples/gateways/example-gateway/go.sum
  examples/gateways/example-gateway/main.go
  examples/gateways/example-gateway/project.yaml
Labels: docs, 2.0

#1578 don't assume a repo's default branch is named master
  sdk/v2/core/events.go
  sdk/v2/core/workers.go
  v2/apiserver/internal/api/events.go
  v2/apiserver/internal/api/workers.go
  v2/cli/init_templates.go
  v2/git-initializer/main.go
Labels: bug, 2.0

#1581 pre-release version bumps
  docs/content/intro/install.md
  docs/content/intro/quickstart.md
  docs/content/topics/operators/deploy.md
  v2/cli/init_templates.go
Labels: 2.0

#1583 fix wrong ldflags on cli build
  scripts/build-cli.sh
Labels: bug, 2.0

#1582 post-release version bumps
  .brigade/package.json
  .brigade/yarn.lock
  examples/07-npm/.brigade/package-lock.json
  examples/07-npm/.brigade/package.json
  examples/08-yarn/.brigade/package.json
  examples/08-yarn/.brigade/yarn.lock
  examples/11-kitchen-sink/.brigade/package.json
  examples/11-kitchen-sink/.brigade/yarn.lock
  examples/gateways/example-gateway/go.mod
  examples/gateways/example-gateway/go.sum
Labels: 2.0

#1577 docs(authorization.md): add authorization doc
  docs/content/topics/administrators/authorization.md
Labels: docs, 2.0

#1591 fix broken worker build
  v2/brigadier-polyfill/package.json
  v2/brigadier-polyfill/yarn.lock
  v2/brigadier/package.json
  v2/brigadier/yarn.lock
  v2/worker/Dockerfile
  v2/worker/package.json
  v2/worker/yarn.lock
Labels: bug, 2.0

#1592 chore: upgrade node
  .brigade/brigade.ts
  Makefile
  v2/worker/Dockerfile
Labels: 2.0

#1593 add event summary field
  sdk/v2/core/events.go
  sdk/v2/core/events_test.go
  sdk/v2/testing/core/mock_events_client.go
  v2/apiserver/internal/api/events.go
  v2/apiserver/internal/api/events_test.go
  v2/apiserver/internal/api/mongodb/events_store.go
  v2/apiserver/internal/api/mongodb/events_store_test.go
  v2/apiserver/internal/api/rest/events_endpoints.go
  v2/apiserver/main.go
  v2/apiserver/schemas/event-summary.json
Labels: 2.0
