Repository brigadecore/brigade, pull requests merged in 2021-06, with the labels that each got.

#1433 post-release version bumps (examples)
  examples/07-npm/.brigade/package-lock.json
  examples/07-npm/.brigade/package.json
  examples/08-yarn/.brigade/package.json
  examples/08-yarn/.brigade/yarn.lock
  examples/11-kitchen-sink/.brigade/package.json
  examples/11-kitchen-sink/.brigade/yarn.lock
Labels: 2.0

#1434 fix usage of -k in README.md
  README.md
Labels: 2.0, docs

#1440 add mocks for all clients in the sdk
  sdk/v2/testing/authn/mock_api_client.go
  sdk/v2/testing/authn/mock_api_client_test.go
  sdk/v2/testing/authn/mock_service_accounts_client.go
  sdk/v2/testing/authn/mock_service_accounts_client_test.go
  sdk/v2/testing/authn/mock_sessions_client.go
  sdk/v2/testing/authn/mock_sessions_client_test.go
  sdk/v2/testing/authn/mock_users_client.go
  sdk/v2/testing/authn/mock_users_client_test.go
  sdk/v2/testing/authz/mock_api_client.go
  sdk/v2/testing/authz/mock_api_client_test.go
  sdk/v2/testing/authz/mock_role_assignments_client.go
  sdk/v2/testing/authz/mock_role_assignments_client_test.go
  sdk/v2/testing/core/mock_api_client.go
  sdk/v2/testing/core/mock_api_client_test.go
  sdk/v2/testing/core/mock_authz_client.go
  sdk/v2/testing/core/mock_authz_client_test.go
  sdk/v2/testing/core/mock_events_client.go
  sdk/v2/testing/core/mock_events_client_test.go
  sdk/v2/testing/core/mock_jobs_client.go
  sdk/v2/testing/core/mock_jobs_client_test.go
  sdk/v2/testing/core/mock_logs_client.go
  sdk/v2/testing/core/mock_logs_client_test.go
  sdk/v2/testing/core/mock_project_role_assignments_client.go
  sdk/v2/testing/core/mock_project_role_assignments_client_test.go
  sdk/v2/testing/core/mock_projects_client.go
  sdk/v2/testing/core/mock_projects_client_test.go
  sdk/v2/testing/core/mock_secrets_client.go
  sdk/v2/testing/core/mock_secrets_client_test.go
  sdk/v2/testing/core/mock_substrate_client.go
  sdk/v2/testing/core/mock_substrate_client_test.go
  sdk/v2/testing/core/mock_workers_client.go
  sdk/v2/testing/core/mock_workers_client_test.go
  sdk/v2/testing/mock_api_client.go
  sdk/v2/testing/mock_api_client_test.go
  sdk/v2/testing/system/mock_api_client.go
  sdk/v2/testing/system/mock_api_client_test.go
Labels: 2.0

#1444 make scheduler and observer use new sdk mock clients
  v2/observer/healthcheck.go
  v2/observer/healthcheck_test.go
  v2/observer/jobs.go
  v2/observer/jobs_test.go
  v2/observer/observer.go
  v2/observer/observer_test.go
  v2/observer/workers.go
  v2/observer/workers_test.go
  v2/scheduler/jobs.go
  v2/scheduler/jobs_test.go
  v2/scheduler/projects.go
  v2/scheduler/projects_test.go
  v2/scheduler/scheduler.go
  v2/scheduler/scheduler_test.go
  v2/scheduler/workers.go
  v2/scheduler/workers_test.go
Labels: 2.0

#1449 add branding to login splash page
  v2/apiserver/Dockerfile
  v2/apiserver/assets/edmondsans-medium.otf
  v2/apiserver/assets/favicon.png
  v2/apiserver/assets/logo.png
  v2/apiserver/assets/splash.css
  v2/apiserver/assets/splash.html
  v2/apiserver/internal/assets/endpoints.go
  v2/apiserver/internal/authn/rest/sessions_endpoints.go
  v2/apiserver/main.go
Labels: 2.0

#1452 fix logs stream authz requirements
  v2/apiserver/internal/core/logs.go
Labels: 2.0

#1457 Limit authn by org
  charts/brigade/templates/apiserver/deployment.yaml
  charts/brigade/values.yaml
  v2/apiserver/config.go
  v2/apiserver/internal/authn/github/third_party_auth_helper.go
Labels: 2.0, security

#1458 add godocs to os package
  v2/internal/os/os.go
Labels: 2.0

#1464 disable failing third party auth test
  v2/apiserver/config_test.go
Labels: 2.0, bug

#1466 fix session ttl
  v2/apiserver/internal/authn/sessions.go
Labels: 2.0, bug, security

#1463 fix slice index out of bounds in k8s log stream
  v2/apiserver/internal/core/kubernetes/logs_store.go
Labels: 2.0, bug

#1459 feat(cli): add output flag to service account create cmd
  v2/cli/flags.go
  v2/cli/service_account_commands.go
Labels: 2.0

#1461 start dogfooding brigade 2
  .brigade/brigade.ts
  .brigade/package.json
  .brigade/project.yaml
  .brigade/yarn.lock
  brigade.js
Labels: 2.0

#1468 validate examples as part of ci
  .brigade/brigade.ts
Labels: 2.0

#1469 subscribed our own brigade 2 project to push events
  .brigade/project.yaml
Labels: 2.0

#1470 fix edge publishing
  .brigade/brigade.ts
Labels: 2.0
