Repository brigadecore/brigade, pull requests merged in 2021-04, with the labels that each got.

#1340 Link to SDK godoc
  sdk/README.md
Labels: 2.0, docs

#1341 add script and make target for standing up a customized kind cluster
  Makefile
  hack/kind/new-cluster.sh
Labels: 2.0

#1338 change how labels work; introduce qualifiers
  sdk/v2/core/events.go
  sdk/v2/core/events_test.go
  sdk/v2/core/labels.go
  sdk/v2/core/projects.go
  sdk/v2/go.sum
  v2/apiserver/internal/core/events.go
  v2/apiserver/internal/core/events_test.go
  v2/apiserver/internal/core/kubernetes/substrate.go
  v2/apiserver/internal/core/labels.go
  v2/apiserver/internal/core/mongodb/events_store.go
  v2/apiserver/internal/core/mongodb/projects_store.go
  v2/apiserver/internal/core/mongodb/projects_store_test.go
  v2/apiserver/internal/core/projects.go
  v2/apiserver/internal/core/qualifiers.go
  v2/apiserver/internal/core/qualifiers_test.go
  v2/apiserver/internal/core/rest/events_endpoints.go
  v2/apiserver/internal/core/rest/events_endpoints_test.go
  v2/apiserver/schemas/event.json
  v2/apiserver/schemas/project.json
  v2/cli/event_commands.go
  v2/cli/flags.go
  v2/go.sum
Labels: 2.0

#1342 API version bump
  README.md
  examples/01-hello-world/project.yaml
  examples/02-first-event/project.yaml
  examples/03-first-job/project.yaml
  examples/04-simple-pipeline/project.yaml
  examples/05-groups/project.yaml
  examples/06-git/project.yaml
  examples/07-npm/project.yaml
  examples/08-yarn/project.yaml
  examples/09-typescript/project.yaml
  examples/10-kitchen-sink/project.yaml
  sdk/v2/meta/meta.go
  v2/apiserver/internal/meta/meta.go
  v2/apiserver/internal/meta/testing/meta.go
  v2/apiserver/schemas/common.json
  v2/brigadier-polyfill/src/jobs.ts
Labels: 2.0

#1346 fix publish cli job
  Makefile
Labels: 2.0, bug

#1347 bump api version in preparation for release
  README.md
  examples/01-hello-world/project.yaml
  examples/02-first-event/project.yaml
  examples/03-first-job/project.yaml
  examples/04-simple-pipeline/project.yaml
  examples/05-groups/project.yaml
  examples/06-git/project.yaml
  examples/07-npm/project.yaml
  examples/08-yarn/project.yaml
  examples/09-typescript/project.yaml
  examples/10-kitchen-sink/project.yaml
  sdk/v2/meta/meta.go
  v2/apiserver/internal/meta/meta.go
  v2/apiserver/internal/meta/testing/meta.go
  v2/apiserver/schemas/common.json
  v2/brigadier-polyfill/src/jobs.ts
Labels: 2.0

#1348 fix publish-cli target
  Makefile
Labels: 2.0, bug

#1350 fix a few spelling errors
  charts/brigade/values.yaml
Labels: 2.0

#1351 update examples to use latest brigadier
  examples/07-npm/.brigade/package-lock.json
  examples/07-npm/.brigade/package.json
  examples/08-yarn/.brigade/package.json
  examples/08-yarn/.brigade/yarn.lock
  examples/10-kitchen-sink/.brigade/package.json
  examples/10-kitchen-sink/.brigade/yarn.lock
Labels: 2.0

#1356 move the PrincipalReference type
  sdk/v2/authz/role_assignments.go
  sdk/v2/authz/role_assignments_test.go
  sdk/v2/core/project_roles_assignments_test.go
  sdk/v2/lib/authz/principals.go
  v2/apiserver/internal/authz/rest/role_assignments_endpoints.go
  v2/apiserver/internal/authz/role_assignments.go
  v2/apiserver/internal/authz/role_assignments_test.go
  v2/apiserver/internal/core/project_role_assignments_test.go
  v2/apiserver/internal/core/projects.go
  v2/apiserver/internal/core/rest/project_role_assignments_endpoints.go
  v2/apiserver/internal/lib/authz/principals.go
  v2/apiserver/internal/system/authz/authorizers.go
Labels: 2.0

#1357 move RoleAssignment type
  sdk/v2/authz/role_assignments.go
  sdk/v2/authz/role_assignments_test.go
  sdk/v2/core/project_role_assignments.go
  sdk/v2/core/project_roles_assignments_test.go
  sdk/v2/lib/authz/role_assignments.go
  v2/apiserver/internal/authz/mock_roles_assignments_store.go
  v2/apiserver/internal/authz/mongodb/role_assignments_store.go
  v2/apiserver/internal/authz/mongodb/role_assignments_store_test.go
  v2/apiserver/internal/authz/rest/role_assignments_endpoints.go
  v2/apiserver/internal/authz/role_assignments.go
  v2/apiserver/internal/authz/role_assignments_test.go
  v2/apiserver/internal/core/project_role_assignments.go
  v2/apiserver/internal/core/project_role_assignments_test.go
  v2/apiserver/internal/core/projects.go
  v2/apiserver/internal/core/projects_test.go
  v2/apiserver/internal/core/rest/project_role_assignments_endpoints.go
  v2/apiserver/internal/lib/authz/role_assignments.go
  v2/apiserver/internal/system/authz/authorizers.go
  v2/apiserver/internal/system/authz/authorizers_test.go
  v2/cli/project_role_commands.go
  v2/cli/role_commands.go
Labels: 2.0

#1358 move Scope field from Role type to RoleAssignment type
  sdk/v2/authz/role_assignments.go
  sdk/v2/authz/role_assignments_test.go
  sdk/v2/core/named_roles.go
  sdk/v2/core/project_role_assignments.go
  sdk/v2/core/project_roles_assignments_test.go
  sdk/v2/lib/authz/role_assignments.go
  sdk/v2/lib/authz/roles.go
  v2/apiserver/internal/authn/service_accounts.go
  v2/apiserver/internal/authn/users.go
  v2/apiserver/internal/authz/mongodb/role_assignments_store.go
  v2/apiserver/internal/authz/rest/role_assignments_endpoints.go
  v2/apiserver/internal/authz/role_assignments.go
  v2/apiserver/internal/core/events.go
  v2/apiserver/internal/core/jobs.go
  v2/apiserver/internal/core/logs.go
  v2/apiserver/internal/core/named_roles.go
  v2/apiserver/internal/core/project_role_assignments.go
  v2/apiserver/internal/core/projects.go
  v2/apiserver/internal/core/rest/project_role_assignments_endpoints.go
  v2/apiserver/internal/core/secrets.go
  v2/apiserver/internal/core/substrate.go
  v2/apiserver/internal/core/workers.go
  v2/apiserver/internal/lib/authz/authorizers.go
  v2/apiserver/internal/lib/authz/role_assignments.go
  v2/apiserver/internal/lib/authz/role_assignments_test.go
  v2/apiserver/internal/lib/authz/roles.go
  v2/apiserver/internal/lib/authz/roles_test.go
  v2/apiserver/internal/system/authn/named_principals.go
  v2/apiserver/internal/system/authz/authorizers.go
  v2/apiserver/internal/system/authz/authorizers_test.go
  v2/cli/project_role_commands.go
  v2/cli/role_commands.go
Labels: 2.0

#1361 brigadier local run fixes
  v2/brigadier/src/events.ts
Labels: 2.0

#1364 simplify role type
  sdk/v2/authz/role_assignments.go
  sdk/v2/authz/role_assignments_test.go
  sdk/v2/core/named_roles.go
  sdk/v2/core/project_role_assignments.go
  sdk/v2/core/project_roles.go
  sdk/v2/core/project_roles_assignments_test.go
  sdk/v2/lib/authz/role_assignments.go
  sdk/v2/lib/authz/roles.go
  sdk/v2/system/named_roles.go
  v2/apiserver/internal/authn/service_accounts.go
  v2/apiserver/internal/authn/users.go
  v2/apiserver/internal/authz/mongodb/role_assignments_store.go
  v2/apiserver/internal/authz/rest/role_assignments_endpoints.go
  v2/apiserver/internal/authz/role_assignments.go
  v2/apiserver/internal/core/authorizers.go
  v2/apiserver/internal/core/authorizers_test.go
  v2/apiserver/internal/core/events.go
  v2/apiserver/internal/core/jobs.go
  v2/apiserver/internal/core/logs.go
  v2/apiserver/internal/core/mongodb/project_role_assignments_store.go
  v2/apiserver/internal/core/named_roles.go
  v2/apiserver/internal/core/project_role_assignments.go
  v2/apiserver/internal/core/project_role_assignments_test.go
  v2/apiserver/internal/core/project_roles.go
  v2/apiserver/internal/core/projects.go
  v2/apiserver/internal/core/rest/project_role_assignments_endpoints.go
  v2/apiserver/internal/core/secrets.go
  v2/apiserver/internal/core/substrate.go
  v2/apiserver/internal/core/workers.go
  v2/apiserver/internal/lib/authz/authorizers.go
  v2/apiserver/internal/lib/authz/role_assignments.go
  v2/apiserver/internal/lib/authz/role_assignments_test.go
  v2/apiserver/internal/lib/authz/roles.go
  v2/apiserver/internal/system/authn/named_principals.go
  v2/apiserver/internal/system/authz/authorizers.go
  v2/apiserver/internal/system/authz/authorizers_test.go
  v2/apiserver/internal/system/named_roles.go
  v2/apiserver/schemas/project-role-assignment.json
  v2/apiserver/schemas/role-assignment.json
  v2/cli/project_role_commands.go
  v2/cli/role_commands.go
Labels: 2.0

#1369 small schema fixes
  v2/apiserver/schemas/project-role-assignment.json
  v2/apiserver/schemas/role-assignment.json
Labels: 2.0, bug

#1372 allow user-defined oidc success redirect
  sdk/v2/authn/sessions.go
  sdk/v2/authn/sessions_test.go
  v2/apiserver/internal/authn/rest/sessions_endpoints.go
  v2/apiserver/internal/authn/sessions.go
  v2/apiserver/internal/authn/sessions_test.go
  v2/apiserver/internal/lib/restmachinery/endpoints.go
  v2/cli/login_command.go
Labels: 2.0

#1368 implement list role assignments & list project role assignments
  sdk/v2/authz/role_assignments.go
  sdk/v2/authz/role_assignments_test.go
  sdk/v2/core/project_role_assignments.go
  sdk/v2/core/project_roles_assignments_test.go
  sdk/v2/lib/authz/role_assignments.go
  sdk/v2/lib/authz/role_assignments_test.go
  v2/apiserver/internal/authz/mock_roles_assignments_store.go
  v2/apiserver/internal/authz/mongodb/role_assignments_store.go
  v2/apiserver/internal/authz/mongodb/role_assignments_store_test.go
  v2/apiserver/internal/authz/rest/role_assignments_endpoints.go
  v2/apiserver/internal/authz/role_assignments.go
  v2/apiserver/internal/authz/role_assignments_test.go
  v2/apiserver/internal/core/mongodb/project_role_assignments_store.go
  v2/apiserver/internal/core/mongodb/project_role_assignments_store_test.go
  v2/apiserver/internal/core/project_role_assignments.go
  v2/apiserver/internal/core/project_role_assignments_test.go
  v2/apiserver/internal/core/rest/project_role_assignments_endpoints.go
  v2/apiserver/internal/lib/authz/role_assignments.go
  v2/apiserver/internal/lib/authz/role_assignments_test.go
  v2/apiserver/main.go
  v2/cli/flags.go
  v2/cli/project_role_commands.go
  v2/cli/role_commands.go
Labels: 2.0

#1375 minor clone cleanup
  sdk/v2/core/events.go
  sdk/v2/core/events_test.go
  v2/apiserver/internal/core/common_test.go
  v2/apiserver/internal/core/events.go
  v2/cli/event_commands.go
Labels: 2.0

#1374 reword event clone command help
  v2/cli/event_commands.go
Labels: 2.0

#1373 add --follow flag to cli event create command
  v2/apiserver/internal/core/kubernetes/logs_store.go
  v2/apiserver/internal/core/logs.go
  v2/cli/event_commands.go
  v2/cli/log_command.go
Labels: 2.0

#1377 add role grant/revoke ack messages to cli
  v2/cli/project_role_commands.go
  v2/cli/role_commands.go
Labels: 2.0

#1367 more flexible options for building/running scripts
  v2/worker/src/prestart.ts
Labels: 2.0, awaiting review

#1380 add an example that uses a shared workspace
  examples/10-shared-workspace/project.yaml
  examples/11-kitchen-sink/.brigade/brigade.ts
  examples/11-kitchen-sink/.brigade/package.json
  examples/11-kitchen-sink/.brigade/yarn.lock
  examples/11-kitchen-sink/project.yaml
Labels: 2.0

#1379 cli: allow secrets to be set from a file
  v2/cli/secret_commands.go
Labels: 2.0

#1381 log streaming: account for initialized pod with container still creating
  v2/apiserver/internal/core/kubernetes/logs_store.go
Labels: 2.0, bug

#1382 use unique names for each integration test
  v2/tests/integration_test.go
Labels: 2.0

#1384 log in using GitHub as identity provider
  charts/brigade/templates/apiserver/deployment.yaml
  charts/brigade/templates/apiserver/secret.yaml
  charts/brigade/values.yaml
  sdk/v2/authn/sessions.go
  sdk/v2/authn/sessions_test.go
  v2/apiserver/config.go
  v2/apiserver/config_test.go
  v2/apiserver/internal/authn/common_test.go
  v2/apiserver/internal/authn/github/third_party_auth_helper.go
  v2/apiserver/internal/authn/github/third_party_auth_helper_test.go
  v2/apiserver/internal/authn/oidc/third_party_auth_helper.go
  v2/apiserver/internal/authn/oidc/third_party_auth_helper_test.go
  v2/apiserver/internal/authn/rest/sessions_endpoints.go
  v2/apiserver/internal/authn/sessions.go
  v2/apiserver/internal/authn/sessions_test.go
  v2/apiserver/internal/authn/third_party_auth_helper.go
  v2/apiserver/internal/system/authn/token_auth.go
  v2/apiserver/internal/system/authn/token_auth_test.go
  v2/apiserver/main.go
  v2/cli/login_command.go
  v2/go.mod
  v2/go.sum
Labels: 2.0

#1389 fix kitchen sink example
  examples/11-kitchen-sink/project.yaml
Labels: 2.0, bug

#1388 make max concurrent workers and jobs configurable during install
  charts/brigade/templates/scheduler/deployment.yaml
  charts/brigade/values.yaml
Labels: 2.0

#1391 Fix marshal job when status is empty
  sdk/v2/core/jobs.go
Labels: 2.0

#1390 streamline first-time login for admins
  charts/brigade/templates/apiserver/deployment.yaml
  charts/brigade/values.yaml
  sdk/v2/core/named_roles.go
  sdk/v2/system/named_roles.go
  v2/apiserver/config.go
  v2/apiserver/internal/authn/sessions.go
  v2/apiserver/internal/authn/sessions_test.go
  v2/apiserver/internal/core/events.go
  v2/apiserver/internal/core/named_roles.go
  v2/apiserver/internal/core/projects.go
  v2/apiserver/internal/system/authn/named_principals.go
  v2/apiserver/internal/system/named_roles.go
  v2/apiserver/main.go
  v2/cli/role_commands.go
  v2/internal/os/os.go
  v2/internal/os/os_test.go
Labels: 2.0

#1394 add system client to the client tree
  sdk/v2/api_client.go
  sdk/v2/api_client_test.go
Labels: 2.0

#1393 small tweak to make event cloning more restful
  sdk/v2/core/events.go
  sdk/v2/core/events_test.go
  v2/apiserver/internal/core/rest/events_endpoints.go
Labels: 2.0
