Repository brigadecore/brigade, pull requests merged in 2021-09, with the labels that each got.

#1586 docs(storage.md): v2 updates
  docs/content/topics/operators/storage.md
Labels: docs, 2.0

#1595 add worker support for event summary field, pt2
  examples/02-first-event/project.yaml
  v2/brigadier-polyfill/package.json
  v2/brigadier-polyfill/src/events.ts
  v2/brigadier-polyfill/yarn.lock
  v2/brigadier/src/events.ts
Labels: 2.0

#1601 use go 1.17 features to improve tests
  .brigade/brigade.ts
  Makefile
  v2/apiserver/Dockerfile
  v2/apiserver/config_test.go
  v2/apiserver/internal/lib/restmachinery/endpoints.go
  v2/cli/secret_commands_test.go
  v2/git-initializer/Dockerfile
  v2/observer/Dockerfile
  v2/observer/config_test.go
  v2/observer/observer_test.go
  v2/scheduler/Dockerfile
  v2/scheduler/config_test.go
  v2/scheduler/scheduler_test.go
Labels: 2.0

#1602 build our own artemis image
  .brigade/brigade.ts
  Makefile
  charts/brigade/templates/artemis/primary-stateful-set.yaml
  charts/brigade/templates/artemis/secondary-stateful-set.yaml
  charts/brigade/templates/artemis/stateful-set.yaml
  charts/brigade/values.yaml
  v2/artemis/Dockerfile
  v2/artemis/docker-entrypoint.sh
  v2/artemis/merge.xslt
Labels: 2.0

#1523 brig term
  v2/cli/main.go
  v2/cli/term/event_page.go
  v2/cli/term/helpers.go
  v2/cli/term/job_page.go
  v2/cli/term/log_page.go
  v2/cli/term/page.go
  v2/cli/term/page_router.go
  v2/cli/term/project_page.go
  v2/cli/term/projects_page.go
  v2/cli/term_command.go
  v2/go.mod
  v2/go.sum
Labels: 2.0

#1599 docs(secrets.md): updates per v2
  docs/content/topics/project-developers/secrets.md
Labels: docs, 2.0

#1614 brigade.ts: fix push-artemis job
  .brigade/brigade.ts
Labels: bug, 2.0

#1621 post release version bumps
  .brigade/package.json
  .brigade/yarn.lock
  examples/07-npm/.brigade/package-lock.json
  examples/07-npm/.brigade/package.json
  examples/08-yarn/.brigade/package.json
  examples/08-yarn/.brigade/yarn.lock
  examples/11-kitchen-sink/.brigade/package.json
  examples/11-kitchen-sink/.brigade/yarn.lock
  examples/gateways/example-gateway/go.mod
  examples/gateways/example-gateway/go.sum
Labels: 2.0

#1620 chart: fix artemis image tags
  charts/brigade/templates/artemis/primary-stateful-set.yaml
  charts/brigade/templates/artemis/secondary-stateful-set.yaml
Labels: bug, 2.0

#1619 fix chart publishing issue
  Makefile
Labels: 2.0

#1604 docs(brig.md): add brig doc
  docs/content/topics/project-developers/brig.md
Labels: docs, 2.0

#1596 docs(events.md): add Events doc
  docs/content/topics/operators/gateways.md
  docs/content/topics/project-developers/events.md
Labels: docs, 2.0

#1588 worker: git sidecar gets pull policy from job config
  brigade-worker/src/k8s.ts
Labels: awaiting review

#1625 mention code of conduct in readme
  README.md
Labels: docs, 2.0

#1609 docs(security.md): v2 updates
  docs/content/topics/operators/security.md
Labels: docs, 2.0

#1639 cli: fix format of user "first seen" column
  v2/cli/user_commands.go
Labels: bug, 2.0, rc-blocker

#1641 add logo to README.md and Chart.yml
  README.md
  charts/brigade/Chart.yaml
  logo.png
Labels: 2.0, rc-blocker

#1633 docs(brigadier): add README.md
  v2/brigadier/README.md
Labels: docs, 2.0

#1647 fix contributing doc link
  CONTRIBUTING.md
  docs/content/topics/contributing.md
Labels: docs, 2.0

#1637 Support more than one brigade instance per cluster
  charts/brigade/templates/apiserver/cluster-role-binding.yaml
  charts/brigade/templates/apiserver/cluster-role.yaml
  charts/brigade/templates/apiserver/deployment.yaml
  charts/brigade/templates/logger/cluster-role-binding.yaml
  charts/brigade/templates/logger/cluster-role.yaml
  charts/brigade/templates/logger/secret.yaml
  charts/brigade/templates/observer/cluster-role-binding.yaml
  charts/brigade/templates/observer/cluster-role.yaml
  charts/brigade/templates/observer/deployment.yaml
  charts/brigade/values.yaml
  docs/content/topics/operators/security.md
  v2/apiserver/config.go
  v2/apiserver/config_test.go
  v2/apiserver/internal/api/kubernetes/substrate.go
  v2/apiserver/internal/api/kubernetes/substrate_test.go
  v2/internal/kubernetes/common.go
  v2/observer/jobs.go
  v2/observer/observer.go
  v2/observer/observer_test.go
  v2/observer/workers.go
Labels: 2.0, rc-blocker

#1632 docs(*): update main docs index; update some urls
  .github/PULL_REQUEST_TEMPLATE.md
  docs/content/_index.md
  docs/content/topics/operators/gateways.md
  docs/content/topics/project-developers/events.md
Labels: docs, 2.0

#1648 Add support for `ingressClassName` to v2 Helm charts
  charts/brigade/templates/_helpers.tpl
  charts/brigade/templates/apiserver/ingress.yaml
  charts/brigade/values.yaml
Labels: 2.0
