Repository brigadecore/brigade, pull requests merged in 2021-05, with the labels that each got.

#1395 improve parsing of secrets from a file
  v2/cli/secret_commands.go
Labels: 2.0, breaking change

#1396 docs(README); add GitHub OAuth note
  README.md
Labels: 2.0, docs

#1397 another improvement to how secrets are parsed from a JSON or YAML file
  v2/cli/secret_commands.go
  v2/cli/secret_commands_test.go
Labels: 2.0

#1404 improve chart work better with cert manager
  charts/brigade/templates/apiserver/cert-secret.yaml
  charts/brigade/templates/apiserver/ingress-cert-secret.yaml
  charts/brigade/templates/apiserver/service.yaml
  charts/brigade/values.yaml
Labels: 2.0

#1407 update examples to use latest brigadier
  examples/07-npm/.brigade/package-lock.json
  examples/07-npm/.brigade/package.json
  examples/08-yarn/.brigade/package.json
  examples/08-yarn/.brigade/yarn.lock
  examples/11-kitchen-sink/.brigade/package.json
  examples/11-kitchen-sink/.brigade/yarn.lock
Labels: 2.0

#1409 cli: remediate issues related to global flags
  v2/cli/client.go
  v2/cli/client_test.go
  v2/cli/common.go
  v2/cli/config.go
  v2/cli/event_commands.go
  v2/cli/log_command.go
  v2/cli/login_command.go
  v2/cli/logout_command.go
  v2/cli/main.go
  v2/cli/project_commands.go
  v2/cli/project_role_commands.go
  v2/cli/role_commands.go
  v2/cli/secret_commands.go
  v2/cli/service_account_commands.go
  v2/cli/user_commands.go
Labels: 2.0

#1416 fix event schema
  v2/apiserver/schemas/common.json
  v2/apiserver/schemas/event.json
  v2/apiserver/schemas/project.json
Labels: 2.0, bug

#1417 Link to contributing guide in Community repo
  CONTRIBUTING.md
Labels: 2.0, docs

#1421 Log access fix
  v2/apiserver/internal/core/logs.go
  v2/apiserver/internal/core/logs_test.go
  v2/apiserver/main.go
Labels: 2.0, bug

#1411 feat(observer): enforce job timeout
  sdk/v2/core/jobs.go
  sdk/v2/core/jobs_test.go
  v2/apiserver/internal/core/jobs.go
  v2/apiserver/internal/core/jobs_test.go
  v2/apiserver/internal/core/kubernetes/substrate.go
  v2/apiserver/internal/core/rest/jobs_endpoints.go
  v2/apiserver/schemas/job.json
  v2/brigadier-polyfill/src/jobs.ts
  v2/brigadier-polyfill/test/jobs.ts
  v2/brigadier/src/jobs.ts
  v2/brigadier/test/jobs.ts
  v2/internal/kubernetes/common.go
  v2/observer/jobs.go
  v2/observer/jobs_test.go
  v2/observer/observer.go
  v2/tests/integration_test.go
Labels: 2.0

#1413 Add project contributor ladder
  CONTRIBUTOR-LADDER.md
Labels: docs

#1426 running yarn upgrade to remediate known vulnerabilities
  v2/brigadier/yarn.lock
  v2/worker/yarn.lock
Labels: 2.0, security
