Repository brigadecore/brigade, pull requests merged in 2021-07, with the labels that each got.

#1472 ci(logger-windows): add CD
  .github/workflows/merge.yaml
  .github/workflows/pr.yaml
  Makefile
Labels: 2.0

#1478 fix nil pointer dereference in observer
  v2/observer/jobs.go
Labels: 2.0, bug

#1479 fix(config_test.go): update ThirdPartyAuthHelper tests to hit test server
  v2/apiserver/config_test.go
Labels: 2.0

#1482 brigade.ts: strip project name from check run name to find job name
  .brigade/brigade.ts
Labels: 2.0, bug

#1480 fix(server_test.go): use different ports for ListenAndServe test variants
  v2/apiserver/internal/lib/restmachinery/server_test.go
Labels: 2.0

#1437 brig init
  sdk/v2/core/projects.go
  sdk/v2/core/projects_test.go
  v2/cli/flags.go
  v2/cli/init_command.go
  v2/cli/init_command_test.go
  v2/cli/init_templates.go
  v2/cli/init_templates_test.go
  v2/cli/main.go
  v2/go.mod
  v2/go.sum
  v2/internal/file/file.go
  v2/internal/file/file_test.go
Labels: 2.0

#1492 Update our own use of Brigade 2
  .brigade/package.json
  .brigade/project.yaml
  .brigade/yarn.lock
Labels: 2.0

#1494 Update examples
  examples/07-npm/.brigade/package-lock.json
  examples/07-npm/.brigade/package.json
  examples/08-yarn/.brigade/package.json
  examples/08-yarn/.brigade/yarn.lock
  examples/11-kitchen-sink/.brigade/package.json
  examples/11-kitchen-sink/.brigade/yarn.lock
Labels: 2.0

#1495 document v2 release procedures
  docs/content/topics/releasing.md
Labels: 2.0

#1497 fix schema for git clone urls
  v2/apiserver/schemas/common.json
Labels: 2.0

#1493 docs(overview.md): update for v2
  docs/content/intro/overview.md
Labels: docs

#1503 add creation date/time stamp to jobs
  sdk/v2/core/jobs.go
  v2/apiserver/internal/core/jobs.go
Labels: 2.0

#1501 docs(README): add mention of beta.1 release
  README.md
Labels: 2.0, docs

#1505 track creation dts for user
  v2/apiserver/internal/authn/sessions.go
Labels: 2.0

#1512 3rd party authn: fix how we check for github org membership
  v2/apiserver/internal/authn/github/third_party_auth_helper.go
  v2/apiserver/internal/authn/github/third_party_auth_helper_test.go
Labels: 2.0, bug

#1510 force cleanup for manually deleted worker and job pods
  v2/observer/common.go
  v2/observer/common_test.go
  v2/observer/jobs.go
  v2/observer/jobs_test.go
  v2/observer/observer.go
  v2/observer/observer_test.go
  v2/observer/workers.go
  v2/observer/workers_test.go
Labels: 2.0

#1515 minor README.md updates
  README.md
Labels: 2.0

#1514 docs(*): align prev/next pagination according to config.toml layout
  docs/config.toml
  docs/content/_index.md
  docs/content/intro/install.md
  docs/content/intro/overview.md
  docs/content/intro/quickstart.md
  docs/content/intro/readnext.md
  docs/content/topics/administrators/_index.md
  docs/content/topics/administrators/authentication.md
  docs/content/topics/administrators/authorization.md
  docs/content/topics/contributing.md
  docs/content/topics/design.md
  docs/content/topics/developers.md
  docs/content/topics/examples.md
  docs/content/topics/operators/_index.md
  docs/content/topics/operators/deploy.md
  docs/content/topics/operators/gateways.md
  docs/content/topics/operators/security.md
  docs/content/topics/operators/storage.md
  docs/content/topics/project-developers/_index.md
  docs/content/topics/project-developers/brigterm.md
  docs/content/topics/project-developers/events.md
  docs/content/topics/project-developers/projects.md
  docs/content/topics/project-developers/secrets.md
  docs/content/topics/releasing.md
  docs/content/topics/roles.md
  docs/content/topics/scripting/_index.md
  docs/content/topics/scripting/advanced.md
  docs/content/topics/scripting/brigadier.md
  docs/content/topics/scripting/dependencies.md
  docs/content/topics/scripting/guide.md
  docs/content/topics/scripting/workers.md
  docs/readme.md
Labels: 2.0, docs
