Repository brigadecore/brigade, pull requests merged in 2021-10, with the labels that each got.

#1658 docs(examples): add links/listing of Brigade examples
  docs/content/topics/examples.md
Labels: docs, 2.0

#1657 lazy event secret creation
  v2/apiserver/internal/api/events.go
  v2/apiserver/internal/api/events_test.go
  v2/apiserver/internal/api/kubernetes/substrate.go
  v2/apiserver/internal/api/kubernetes/substrate_test.go
  v2/apiserver/internal/api/mongodb/workers_store.go
  v2/apiserver/internal/api/mongodb/workers_store_test.go
  v2/apiserver/internal/api/substrate.go
  v2/apiserver/internal/api/substrate_test.go
  v2/apiserver/internal/api/workers.go
  v2/apiserver/internal/api/workers_test.go
Labels: 2.0

#1700 chore: run go mod tidy to remove unused modules
  v2/go.mod
  v2/go.sum
Labels: 2.0, rc-blocker

#1704 update logo in docs
  docs/static/img/brigade.png
Labels: docs, 2.0, rc-blocker

#1703 remove 2.0 proposal from v2 branch
  2.0-PROPOSAL/README.md
  2.0-PROPOSAL/authentication.png
  2.0-PROPOSAL/components.png
  2.0-PROPOSAL/domain.png
  2.0-PROPOSAL/events.png
Labels: docs, 2.0
