Repository brigadecore/brigade, pull requests merged in 2022-01, with the labels that each got.

#1773 bug: fix user list endpoint
  v2/apiserver/internal/api/rest/users_endpoints.go
Labels: bug

#1766 use brigade 2 for brigade 1.x ci/cd
  .brigade/brigade.ts
  .brigade/package.json
  .brigade/yarn.lock
  .gitignore
  Makefile
  brig/.dockerignore
  brigade-api/.dockerignore
  brigade-controller/.dockerignore
  brigade-cr-gateway/.dockerignore
  brigade-generic-gateway/.dockerignore
  brigade-vacuum/.dockerignore
  brigade-worker/.dockerignore
  brigade.js
  brigade.json
  e2e/run.sh
  e2e/wait-for-deployment.sh
  git-sidecar/.dockerignore
Labels: v1

#1775 post-release version bumps
  .brigade/package.json
  .brigade/yarn.lock
  examples/09-npm/.brigade/package-lock.json
  examples/09-npm/.brigade/package.json
  examples/10-yarn/.brigade/package.json
  examples/10-yarn/.brigade/yarn.lock
  examples/12-kitchen-sink/.brigade/package.json
  examples/12-kitchen-sink/.brigade/yarn.lock
  examples/gateways/example-gateway/go.mod
  examples/gateways/example-gateway/go.sum
Labels: chore

#1778 update v1 docs link in v2 docs banner
  docs/themes/techdoc-brigade/layouts/partials/header.html
Labels: docs, chore

#1777 cli: test connection to api server before returning to caller
  v2/cli/client.go
  v2/cli/client_test.go
  v2/cli/event_commands.go
  v2/cli/log_command.go
  v2/cli/logout_command.go
  v2/cli/project_commands.go
  v2/cli/project_role_commands.go
  v2/cli/role_commands.go
  v2/cli/secret_commands.go
  v2/cli/service_account_commands.go
  v2/cli/term_command.go
  v2/cli/user_commands.go
  v2/cli/version_command.go
Labels: bug

#1783 Support option to create non-existing project on update
  sdk/v3/core/common.go
  sdk/v3/core/jobs.go
  sdk/v3/core/jobs_test.go
  sdk/v3/core/logs.go
  sdk/v3/core/projects.go
  sdk/v3/core/projects_test.go
  sdk/v3/core/workers.go
  sdk/v3/core/workers_test.go
  v2/apiserver/internal/api/projects.go
  v2/apiserver/internal/api/projects_test.go
  v2/apiserver/internal/api/rest/projects_endpoints.go
  v2/cli/flags.go
  v2/cli/project_commands.go
Labels: enhancement

#1790 remediate vulnerable npm packages
  v2/brigadier-polyfill/package.json
  v2/brigadier-polyfill/yarn.lock
  v2/brigadier/package.json
  v2/brigadier/yarn.lock
  v2/worker/package.json
  v2/worker/yarn.lock
Labels: security

#1792 take advantage of github gateway's new ci/cd abstraction
  .brigade/brigade.ts
  .brigade/project.yaml
Labels: chore
