Repository brigadecore/brigade, pull requests merged in 2022-03, with the labels that each got.

#1848 add netlify.toml
  netlify.toml
Labels: docs, chore

#1858 readme: update project heading
  README.md
Labels: docs, chore

#1860 Updates README.md with cron-event-source and added "Noisy Neighbor" the the list
  README.md
Labels: docs

#1859 update docs/README.md
  README.md
  docs/README.md
  docs/readme.md
Labels: docs

#1871 update all images to present less attackable surface
  Makefile
  v2/apiserver/Dockerfile
  v2/apiserver/internal/api/kubernetes/substrate.go
  v2/artemis/Dockerfile
  v2/git-initializer/Dockerfile
  v2/logger/Dockerfile
  v2/observer/Dockerfile
  v2/scheduler/Dockerfile
  v2/worker/Dockerfile
  v2/worker/package.json
  v2/worker/src/prestart.ts
  v2/worker/yarn.lock
Labels: security

#1875 scan images as part of the CI process
  .brigade/brigade.ts
  Makefile
Labels: security

#1885 ci: minor improvement to PublishSBOMJob class
  .brigade/brigade.ts
Labels: security

#1887 upgrade docker-tools to v0.3.0
  .brigade/brigade.ts
Labels: bug, security

#1889 release: sign images
  .brigade/brigade.ts
  Makefile
Labels: security

#1890 update CODEOWNERS
  CODEOWNERS
Labels: security

#1891 upgrade artemis to 2.19.1
  v2/artemis/Dockerfile
Labels: bug, chore

#1892 fix nightly cleanup job
  .brigade/brigade.ts
  scripts/nightly-cleanup.sh
Labels: bug

#1894 Makefile: fix publish-sbom-% target
  Makefile
Labels: bug, security, chore

#1896 run first stage of worker build only on native architecture
  v2/worker/Dockerfile
Labels: chore

#1898 make nightly cleanup job use source
  .brigade/brigade.ts
Labels: bug

#1901 upgrade docker-tools to v0.4.0
  .brigade/brigade.ts
Labels: chore
