Repository brigadecore/brigade, pull requests merged in 2022-05, with the labels that each got.

#1939 re-implement git-initializer component using git2go
  Makefile
  golangci.yaml
  v2/git-initializer-windows/Dockerfile
  v2/git-initializer/Dockerfile
  v2/git-initializer/credentials.go
  v2/git-initializer/events.go
  v2/git-initializer/main.go
  v2/git-initializer/main_test.go
  v2/git-initializer/refs.go
  v2/git-initializer/repos.go
  v2/go.mod
  v2/go.sum
  v2/tests/testcases_test.go
Labels: bug

#1950 Revert "re-implement git-initializer component using git2go (#1939)"
  Makefile
  golangci.yaml
  v2/git-initializer-windows/Dockerfile
  v2/git-initializer/Dockerfile
  v2/git-initializer/credentials.go
  v2/git-initializer/events.go
  v2/git-initializer/main.go
  v2/git-initializer/main_test.go
  v2/git-initializer/refs.go
  v2/git-initializer/repos.go
  v2/go.mod
  v2/go.sum
  v2/tests/testcases_test.go
Labels: bug

#1952 make git-initializer work with Azure DevOps
  v2/git-initializer-windows/Dockerfile
  v2/git-initializer/Dockerfile
  v2/git-initializer/auth.go
  v2/git-initializer/cmd.go
  v2/git-initializer/config.go
  v2/git-initializer/crypto.go
  v2/git-initializer/doc.go
  v2/git-initializer/events.go
  v2/git-initializer/main.go
  v2/git-initializer/main_test.go
  v2/git-initializer/repos.go
  v2/git-initializer/ssh_config
  v2/tests/testcases_test.go
Labels: bug

#1954 chore: update the PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#1956 pre-release version bumps
  docs/content/intro/quickstart.md
  docs/content/topics/operators/deploy.md
  docs/content/topics/project-developers/brig.md
  docs/content/topics/scripting/brigadier.md
  v2/cli/init_templates.go
Labels: chore

#1957 post-release version bumps
  .brigade/package.json
  .brigade/yarn.lock
  examples/09-npm/.brigade/package-lock.json
  examples/09-npm/.brigade/package.json
  examples/10-yarn/.brigade/package.json
  examples/10-yarn/.brigade/yarn.lock
  examples/12-kitchen-sink/.brigade/package.json
  examples/12-kitchen-sink/.brigade/yarn.lock
Labels: chore

#1958 fix project update failure if project doesn't exist and not logged in as root
  v2/apiserver/internal/api/projects.go
  v2/apiserver/internal/api/projects_test.go
Labels: bug

#1960 docs: fix invalid code fences
  sdk/README.md
Labels: bug, docs, chore

#1967 make username comparisons case insensitive on initial authn
  v2/apiserver/internal/api/sessions.go
Labels: enhancement

#1973 upgrade sdk-for-js to address CVE-2022-1650
  v2/brigadier-polyfill/package.json
  v2/brigadier-polyfill/yarn.lock
  v2/worker/yarn.lock
Labels: security, chore
